name: Auto-assign PR author

on:
    pull_request_target:
        types: [opened, reopened, ready_for_review]

permissions:
    pull-requests: write

jobs:
    assign:
        if: ${{ github.actor != 'dependabot[bot]' && github.actor != 'renovate[bot]' }}
        runs-on: ubuntu-latest
        steps:
            -   name: Assign PR to its author
                uses: actions/github-script@v7
                with:
                    script: |
                        const { owner, repo } = context.repo;
                        const pr = context.payload.pull_request;
                        await github.rest.issues.addAssignees({
                          owner,
                          repo,
                          issue_number: pr.number,
                          assignees: [pr.user.login]
                        });
